### ISSUE TITLE
Retries occur on error regardless of options

### ISSUE THREAD

**Issue by matthewloring** [stephenplusplus/retry-request#9]
`request` seems to ignore `opts.retries` and `opts.shouldRetryFn` in the case of an error. Culprit line appears to be here: https://github.com/stephenplusplus/retry-request/blob/894670a438d02eb465b432aadecb49131a6a7671/index.js#L108.

**Comment by stephenplusplus** [comment]
This was an intentional recent change considered as a bug fix/enhancement of this library, to retry when it faces an error during transmission of the request. The user's retries setting isn't counted against these attempts, because we considered this expected behavior. The types of errors caught here aren't 404s or 500s, or any server response error. They are only things like DNS resolution/socket hang ups, things that, as a convenience library, we didn't think the user should have to ask us to retry for.

I'm very interested in your thoughts and experience if this was a poor decision. It was meant to be unnoticeable.

**Comment by matthewloring** [comment]
We use `opts.retries` in testing to ensure that the library never retries. There are cases we want to test where we emulate network errors with nock (https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/5080bfc306c34e03487fa90389c3952e276cab9e/test/test-agent-metadata.js#L92). The errors generated by nock follow the code path in this module that does not respect `opts.retries`. If this is desired behavior, we can use the `request` module directly for our use case.
